name: $(Rev:r)

trigger: none
pr: none

parameters:
  - name: cluster
    displayName: 
    type: string
    values:
     - mazcacitprdacloudbeesaks01

variables:
  - group: cex_jenkins_api
  - group: aks_service_principals
  # remove once fully on ADO and reference is removed from the cluster-connect.sh scripts
  - name: STAGE_NAME
    value: task

extends:
  template: cluster-pipeline.yml
  parameters:
    name: run_maven
    displayName: Run Maven
    cluster: ${{ parameters.cluster }}
    script: |
      rm -rf /root/.m2/
      curl -LO https://dlcdn.apache.org/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz && tar -xzf apache-maven-3.9.2-bin.tar.gz -C /opt
      export JAVA_HOME=/usr/local/openjdk-8
      /opt/apache-maven-3.9.2/bin/mvn -v
      /opt/apache-maven-3.9.2/bin/mvn -B -DskipTests clean package
      