name: $(Rev:r)

resources:
  repositories:
    - repository: shared
      type: github
      endpoint: svcdawsdev
      name: RogersCommunications/enterprise-ado-pipelines
      ref: refs/heads/feature/maven

extends:
  template: maven.yml@shared
  parameters:
    repo: cdk-docker-virtual
    # artifactory: artifactory-service
    jdk: '11'
    disabled_stage:
      - integration-tests
      - problem-detection
      - source-stats
      - info
#      - unit-tests
      - validation
      - quality-gate
      - gates
