name: $(Rev:r)

trigger: none
pr: none

parameters:
  - name: cluster
    displayName: 
    type: string
    values:
     - mazcacitprdacloudbeesaks01

variables:
  - group: cex_jenkins_api
  - group: aks_service_principals
  # remove once fully on ADO and reference is removed from the cluster-connect.sh scripts
  - name: STAGE_NAME
    value: task

extends:
  template: cluster-pipeline.yml
  parameters:
    name: run_maven
    displayName: Run Maven
    cluster: ${{ parameters.cluster }}
    script: |
      curl -LO https://dlcdn.apache.org/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz && tar -xzf apache-maven-3.9.2-bin.tar.gz -C /opt
      ln -s /opt/apache-maven-3.9.2 /opt/maven
      mvn -B -DskipTests clean package
      