parameters:
  - name: name
    type: string
    default: detect_cloud
  - name: cluster
    type: string
  - name: depends
    type: object
    default: [ ]        

jobs:
  - job: ${{ parameters.name }}
    displayName: Detect Cloud Provider for ${{ parameters.cluster }}
    pool: k8s-deploytools
    dependsOn:
      - ${{ parameters.depends }}   
    steps:
      - script: |
          CLOUD=$(yq '.[] | select(.clusters | any_c(. == "${{ parameters.cluster }}")) | .type' clusters.yml)
          if [ "${CLOUD}" == 'aws' ]; then
            CLOUD=AWS
          elif [ "${CLOUD}" == 'azure' ]; then
            CLOUD=Azure
          else
            CLOUD=UNKNOWN
          fi
          
          echo "CLOUD='${CLOUD}'"
          echo "##vso[task.setvariable variable=CLOUD;isoutput=true]${CLOUD}"
        name: cloud
        displayName: Detect Cloud Provider